### ISSUE TITLE
[REQUEST] Custom font setting

### ISSUE THREAD

**Issue by hl2guide** [aristocratos/btop4win#16]
**Is your feature request related to a problem? Please describe.**
Custom font support would be nice (e.g. Iosevka).

**Describe the solution you'd like**
Please allow us to set a custom font within main menu and the `btop.conf` file.

**Describe alternatives you've considered**
Setting default for window manually.

**Additional context**
N/A

**Comment by aristocratos** [comment]
@hl2guide
This is terminal software, it's agnostic to what terminal emulator you are using and it certainly can't change font of your particular terminal.
