### ISSUE TITLE
[REQUEST] Support for direct access within Windows Terminal

### ISSUE THREAD

**Issue by hl2guide** [aristocratos/btop4win#17]
**Is your feature request related to a problem? Please describe.**
Currently `btop4win.exe` runs as a separate `command prompt` window when run in `Windows Terminal`.

**Describe the solution you'd like**
Please run directly within Windows Terminal if executed there.

**Describe alternatives you've considered**
Using as normal.

**Additional context**
N/A

**Comment by pplmx** [comment]
Maybe you can try this. FYI.
```bash
# First
scoop install gsudo
# or winget
winget install gerardog.gsudo

# Then
sudo btop
```

**Comment by ZXSwire3** [comment]
doesn't seem to work using sudo btop, at least for me. I run it and still opens a new window. The only way that I was able to get it to work was by running the windows terminal as administrator and then using the btop command to start it. Maybe I'm just doing something wrong, but it would be nice to be able to run more easily

**Comment by pplmx** [comment]
@ZXSwire3 
Try `gsudo`?
