### ISSUE TITLE
btop4win crashes during certain file operations

### ISSUE THREAD

**Issue by drwitwicki** [aristocratos/btop4win#3]
certain kinds of file operations seem to cause the program to suddenly quit. I've noticed this happening when doing things like: saving a file from the web, accessing external drive in windows explorer, or even simply launching an explorer window. I believe it is tied to the delay caused by waking up my external hard drive, which is a spinning disk and takes a few seconds to wake up. I notice every time btop has crashed in this way it was when my drive was waking from sleep. I've included the error message from the log:

`ERROR: Stall in Runner thread, quitting!`

**Comment by aristocratos** [comment]
Sounds like the disk is in dire need of replacing if it stalls for several seconds when writing to it ;)

I will look in to adding a timeout for the disk detection that ignores any disk that times out.

**Comment by aristocratos** [comment]
@drwitwicki 
I've made some changes so stalls will be ignored unless it's greater than 1 minute, try with the attached binary.
You might still get some warnings in the logfile when it stalls, but will keep running.
[btop4win-TestRelease-LHM.zip](https://github.com/aristocratos/btop4win/files/9458671/btop4win-TestRelease-LHM.zip)

**Comment by aristocratos** [comment]
Should be fixed in v1.0.2
