### ISSUE TITLE
[BUG] btop.conf not created for fresh new usage

### ISSUE THREAD

**Issue by hl2guide** [aristocratos/btop4win#6]
**Describe the bug**

btop.conf is not created for a fresh new usage.

**To Reproduce**

1. Extract btop to fresh new folder
2. Launch app and make one change in the options
3. Exit the app
4. btop.conf is not created

**Expected behavior**

btop.conf created after first fresh launch.

**Info (please complete the following information):**
 - btop4win version: 1.0.2 (LHM)
 - Binary: github release
 - Architecture: 64bit
 - Windows Version: 11
 - Terminal used: Windows Terminal
 - Font used: default

**Comment by aristocratos** [comment]
@hl2guide 
1. Can you create files manually in the btop4win folder? (Right click New->Text file, for example).
2. Does it work if you move the btop4win folder to your desktop.
3. Are you changing the same option? If so, which option?
4. Does it work if you make random changes to multiple options?

**Comment by hl2guide** [comment]
1. Yes
2. No
3. Graph Symbol to: Block
4. No (I changed theme and symbol to braille)
5. No

**Comment by aristocratos** [comment]
How are you launching the program?

**Comment by hl2guide** [comment]
> How are you launching the program?

Running btop4win.exe

**Comment by hl2guide** [comment]
I found out that it's because I'm closing window with `X` instead of the menu.

**Comment by aristocratos** [comment]
I've added a handler that detects when closing by using the window controls on the terminal, will be included in the next release.
Honestly didn't know that Windows just kills the process when closing the window manually...

I've tested i locally but you can try this binary until next release: 
[Release-LHM-test.zip](https://github.com/aristocratos/btop4win/files/9482353/Release-LHM-test.zip)

**Comment by eggbean** [comment]
What's the location for `btop.conf` on Windows? I have installed using scoop.
